# Generated by Django 5.1.4 on 2025-01-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='ubicacion',
            field=models.CharField(default='Chile', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.CharField(default='Novela', max_length=50),
            preserve_default=False,
        ),
    ]
