# Generated by Django 5.1.4 on 2025-01-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosaseo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='descripcion default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
