# Generated by Django 5.1.4 on 2025-01-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=3)),
                ('emp_nombre', models.CharField(max_length=200)),
                ('emp_correo', models.EmailField(max_length=254)),
                ('emp_designacion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
