# Generated by Django 5.1.4 on 2025-01-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_manufacturer_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(default='pais', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='d_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
