# Generated by Django 4.2.16 on 2024-12-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=200)),
                ('valoracion', models.IntegerField(default=0, help_text='Valor entre 0 y 10000')),
            ],
            options={
                'permissions': (('es_miembro_uno', 'Es miembro con prioridad uno'),),
            },
        ),
    ]
