# Generated by Django 4.2.16 on 2024-12-11 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardsmodel',
            options={'permissions': (('es_miembro_uno', 'Es miembro con prioridad uno'), ('development', 'Permiso como desarrollador'), ('scrum_master', 'Permiso como scrum master'), ('product_owner', 'Permiso como Product Owner'))},
        ),
    ]
