# Generated by Django 4.2.16 on 2024-12-12 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_boardsmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardsmodel',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardsmodel',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
